class_name GameEnums

enum GameMode { MAIN_RUN, ENDLESS, ANCIENT_REALM }
enum DaoHeart { ASK_DAO, ENLIGHTEN, PROVE_DAO }
enum AffixCategory { SKILL, SPELL, CONSTITUTION, DIVINE, SYNERGY, COMPANION }
enum Quality { COMMON, RARE, EPIC, LEGENDARY, DAO }
enum Element { NONE, FIRE, WATER, THUNDER, WOOD, EARTH, CHAOS }
enum StatusType { BURN, SLOW, PARALYZE, POISON }
enum TriggerType { PASSIVE, ON_HIT }
enum EffectType {
	FLAT_ATTACK,
	FLAT_DEFENSE,
	FLAT_MAX_HP,
	MULT_ATTACK,
	MULT_CRIT_RATE,
	MULT_CRIT_MULT,
	MULT_ATTACK_SPEED,
	MULT_DAO,
	ON_HIT_STATUS,
	PROJECTILE_PIERCE,
}
